dist: xenial
language: python
sudo: false

python:
  - 3.8

env:
  global:
    - LOG_FILE=errors.log

install:
  - pip install tox codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}"

services:
  - redis
